{{- if .Values.airflow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pricepoint.fullname" . }}-airflow-webserver
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pricepoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: airflow-webserver
  template:
    metadata:
      labels:
        {{- include "pricepoint.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
          args: ["webserver"]
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "pricepoint.fullname" . }}-config
          resources:
            {{- toYaml .Values.airflow.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pricepoint.fullname" . }}-airflow-scheduler
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pricepoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: airflow-scheduler
  template:
    metadata:
      labels:
        {{- include "pricepoint.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
          args: ["scheduler"]
          envFrom:
            - configMapRef:
                name: {{ include "pricepoint.fullname" . }}-config
          resources:
            {{- toYaml .Values.airflow.resources | nindent 12 }}
{{- end }}
