apiVersion: v1
kind: Service
metadata:
  name: {{ include "pricepoint.fullname" . }}-api
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
  selector:
    {{- include "pricepoint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
