apiVersion: v1
kind: Service
metadata:
  name: {{ include "pricepoint.fullname" . }}-mlflow
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
spec:
  type: {{ .Values.mlflow.service.type }}
  ports:
    - port: {{ .Values.mlflow.service.port }}
      targetPort: {{ .Values.mlflow.service.port }}
      protocol: TCP
  selector:
    {{- include "pricepoint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
