{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pricepoint.fullname" . }}-api
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      {{- include "pricepoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "pricepoint.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: frontend
      ports:
        - port: {{ .Values.api.service.port }}
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - port: {{ .Values.api.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pricepoint.fullname" . }}-postgres
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  podSelector:
    matchLabels:
      {{- include "pricepoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "pricepoint.selectorLabels" . | nindent 14 }}
      ports:
        - port: 5432
{{- end }}
