{{- if .Values.podDisruptionBudget.enabled }}
{{- if gt (int .Values.api.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pricepoint.fullname" . }}-api
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "pricepoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
---
{{- if gt (int .Values.frontend.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pricepoint.fullname" . }}-frontend
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "pricepoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
{{- end }}
