"""Add Wake County property staging table

Revision ID: 2a19864e3db0
Revises: d5a9e4c7f8b2
Create Date: 2026-02-09 18:47:55.438641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a19864e3db0"
down_revision: str | None = "d5a9e4c7f8b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staging_wake_county_property_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_1", sa.String(length=35), nullable=True),
        sa.Column("owner_2", sa.String(length=35), nullable=True),
        sa.Column("address_1", sa.String(length=35), nullable=True),
        sa.Column("address_2", sa.String(length=35), nullable=True),
        sa.Column("address_3", sa.String(length=35), nullable=True),
        sa.Column("reid", sa.String(length=7), nullable=True),
        sa.Column("card_num", sa.String(length=3), nullable=True),
        sa.Column("num_cards", sa.String(length=3), nullable=True),
        sa.Column("street_num", sa.String(length=6), nullable=True),
        sa.Column("street_prefix", sa.String(length=2), nullable=True),
        sa.Column("street_name", sa.String(length=25), nullable=True),
        sa.Column("street_type", sa.String(length=4), nullable=True),
        sa.Column("street_suffix", sa.String(length=2), nullable=True),
        sa.Column("street_misc", sa.String(length=2), nullable=True),
        sa.Column("planning_jurisdiction", sa.String(length=2), nullable=True),
        sa.Column("township", sa.String(length=2), nullable=True),
        sa.Column("fire_district", sa.String(length=2), nullable=True),
        sa.Column("physical_city", sa.String(length=50), nullable=True),
        sa.Column("physical_zip_code", sa.String(length=5), nullable=True),
        sa.Column("city", sa.String(length=3), nullable=True),
        sa.Column("parcel_identification", sa.String(length=19), nullable=True),
        sa.Column("billing_class", sa.String(length=1), nullable=True),
        sa.Column("land_classification", sa.String(length=1), nullable=True),
        sa.Column("zoning", sa.String(length=5), nullable=True),
        sa.Column("deeded_acreage", sa.Float(), nullable=True),
        sa.Column("special_district_1", sa.String(length=3), nullable=True),
        sa.Column("special_district_2", sa.String(length=3), nullable=True),
        sa.Column("special_district_3", sa.String(length=3), nullable=True),
        sa.Column("land_sale_price", sa.Float(), nullable=True),
        sa.Column("land_sale_date", sa.String(length=10), nullable=True),
        sa.Column("total_sale_price", sa.Float(), nullable=True),
        sa.Column("total_sale_date", sa.String(length=10), nullable=True),
        sa.Column("assessed_building_value", sa.Float(), nullable=True),
        sa.Column("assessed_land_value", sa.Float(), nullable=True),
        sa.Column("deed_book", sa.String(length=6), nullable=True),
        sa.Column("deed_page", sa.String(length=6), nullable=True),
        sa.Column("deed_date", sa.String(length=10), nullable=True),
        sa.Column("property_description", sa.String(length=40), nullable=True),
        sa.Column("vcs", sa.String(length=7), nullable=True),
        sa.Column("property_index", sa.String(length=40), nullable=True),
        sa.Column("type_use", sa.String(length=3), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("num_rooms", sa.Integer(), nullable=True),
        sa.Column("units", sa.Integer(), nullable=True),
        sa.Column("heated_area", sa.Float(), nullable=True),
        sa.Column("utilities", sa.String(length=3), nullable=True),
        sa.Column("street_pavement", sa.String(length=1), nullable=True),
        sa.Column("topography", sa.String(length=1), nullable=True),
        sa.Column("year_of_addition", sa.Integer(), nullable=True),
        sa.Column("effective_year", sa.Integer(), nullable=True),
        sa.Column("remodeled_year", sa.Integer(), nullable=True),
        sa.Column("unused", sa.String(length=2), nullable=True),
        sa.Column("special_write_in", sa.String(length=8), nullable=True),
        sa.Column("story_height", sa.String(length=1), nullable=True),
        sa.Column("design_style", sa.String(length=1), nullable=True),
        sa.Column("foundation_basement", sa.String(length=1), nullable=True),
        sa.Column("foundation_basement_pct", sa.String(length=2), nullable=True),
        sa.Column("exterior_wall", sa.String(length=1), nullable=True),
        sa.Column("common_wall", sa.String(length=1), nullable=True),
        sa.Column("roof", sa.String(length=1), nullable=True),
        sa.Column("roof_floor_system", sa.String(length=1), nullable=True),
        sa.Column("floor_finish", sa.String(length=1), nullable=True),
        sa.Column("interior_finish", sa.String(length=1), nullable=True),
        sa.Column("interior_finish_1", sa.String(length=1), nullable=True),
        sa.Column("interior_finish_1_pct", sa.String(length=2), nullable=True),
        sa.Column("interior_finish_2", sa.String(length=1), nullable=True),
        sa.Column("interior_finish_2_pct", sa.String(length=2), nullable=True),
        sa.Column("heat", sa.String(length=1), nullable=True),
        sa.Column("heat_pct", sa.String(length=2), nullable=True),
        sa.Column("air", sa.String(length=1), nullable=True),
        sa.Column("air_pct", sa.String(length=2), nullable=True),
        sa.Column("bath", sa.String(length=1), nullable=True),
        sa.Column("bath_fixtures", sa.String(length=3), nullable=True),
        sa.Column("builtin_1_description", sa.String(length=15), nullable=True),
        sa.Column("builtin_2_description", sa.String(length=15), nullable=True),
        sa.Column("builtin_3_description", sa.String(length=15), nullable=True),
        sa.Column("builtin_4_description", sa.String(length=15), nullable=True),
        sa.Column("builtin_5_description", sa.String(length=15), nullable=True),
        sa.Column("grade", sa.String(length=5), nullable=True),
        sa.Column("assessed_grade_difference", sa.String(length=3), nullable=True),
        sa.Column("accrued_assessed_condition_pct", sa.String(length=3), nullable=True),
        sa.Column("land_deferred_code", sa.String(length=1), nullable=True),
        sa.Column("land_deferred_amount", sa.Float(), nullable=True),
        sa.Column("historic_deferred_code", sa.String(length=1), nullable=True),
        sa.Column("historic_deferred_amount", sa.Float(), nullable=True),
        sa.Column("recycled_units", sa.Integer(), nullable=True),
        sa.Column("disqualifying_qualifying_flags", sa.String(length=1), nullable=True),
        sa.Column("land_disqualify_qualify_flag", sa.String(length=1), nullable=True),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_staging_wake_county_property_data_reid"),
        "staging_wake_county_property_data",
        ["reid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_staging_wake_county_property_data_reid"),
        table_name="staging_wake_county_property_data",
    )
    op.drop_table("staging_wake_county_property_data")
    # ### end Alembic commands ###
