"""Add staging redfin listings table

Revision ID: e3b7f1c9d4a6
Revises: 2a19864e3db0
Create Date: 2026-02-09 21:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3b7f1c9d4a6"
down_revision: str | None = "2a19864e3db0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staging_redfin_listings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("zip_code", sa.String(), nullable=True),
        sa.Column("listing_status", sa.String(), nullable=True),
        sa.Column("sold_date", sa.String(), nullable=True),
        sa.Column("sold_price", sa.String(), nullable=True),
        sa.Column("listing_price", sa.String(), nullable=True),
        sa.Column("beds", sa.Integer(), nullable=True),
        sa.Column("baths", sa.Float(), nullable=True),
        sa.Column("sqft", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("lot_size", sa.String(), nullable=True),
        sa.Column("price_per_sqft", sa.String(), nullable=True),
        sa.Column("listing_agent", sa.String(), nullable=True),
        sa.Column("listing_brokerage", sa.String(), nullable=True),
        sa.Column("buying_agent", sa.String(), nullable=True),
        sa.Column("buying_brokerage", sa.String(), nullable=True),
        sa.Column("redfin_estimate", sa.String(), nullable=True),
        sa.Column("sale_history", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("tax_history", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("property_details", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("schools", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("climate_flood_factor", sa.String(), nullable=True),
        sa.Column("climate_fire_factor", sa.String(), nullable=True),
        sa.Column("photo_s3_paths", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("source_file", sa.String(), nullable=True),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_staging_redfin_listings_address"),
        "staging_redfin_listings",
        ["address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_staging_redfin_listings_address"),
        table_name="staging_redfin_listings",
    )
    op.drop_table("staging_redfin_listings")
    # ### end Alembic commands ###
