{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pricepoint.fullname" . }}-airflow
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-webserver
spec:
  type: {{ .Values.airflow.webserver.service.type }}
  ports:
    - port: {{ include "pricepoint.airflowPort" . }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "pricepoint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-webserver
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pricepoint.fullname" . }}-airflow-scheduler
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-scheduler
spec:
  clusterIP: None
  ports:
    - port: 8793
      targetPort: 8793
      protocol: TCP
      name: logs
  selector:
    {{- include "pricepoint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-scheduler
{{- end }}
