{{- if and .Values.ingress.enabled .Values.martin.enabled -}}
{{- if hasPrefix "traefik" (.Values.ingress.className | default "") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pricepoint.fullname" . }}-strip-tiles
  labels:
    {{- include "pricepoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: martin
spec:
  stripPrefix:
    prefixes:
      - /tiles
{{- end }}
{{- end }}
