/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness probe — returns 200 if the service is running.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ready
     * @description Readiness probe — checks database connectivity.
     *
     *     Returns 200 if the database is reachable, 503 otherwise.
     */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Create a new user account.
     */
    post: operations["register_api_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Authenticate and return a JWT access token.
     */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Me
     * @description Return the current authenticated user's profile.
     */
    get: operations["get_me_api_auth_me_get"];
    /**
     * Update Me
     * @description Update the current user's display name.
     */
    put: operations["update_me_api_auth_me_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Google Login
     * @description Redirect the user to Google's OAuth consent screen.
     */
    get: operations["google_login_api_auth_google_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/google/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Google Callback
     * @description Handle the OAuth callback from Google.
     *
     *     Exchanges the authorization code for tokens, fetches user info, then
     *     either logs in an existing user, links a Google account, or creates a
     *     new account.
     */
    get: operations["google_callback_api_auth_google_callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/forecast": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Forecast
     * @description Return a home value forecast for the given address.
     *
     *     Geocodes the address, builds features, and runs the production model.
     *     Falls back gracefully when MLflow is unavailable.
     */
    post: operations["forecast_api_forecast_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/forecast/importance/{property_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Feature Importance
     * @description Return feature importance attributions for a property prediction.
     *
     *     Loads the production model's global feature importances weighted by
     *     the property's feature values.  Returns top 10 positive and top 10
     *     negative contributors.  Falls back to stub data when MLflow is
     *     unavailable.
     */
    get: operations["feature_importance_api_forecast_importance__property_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/geocode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Geocode
     * @description Look up addresses via Nominatim, with optional Valkey caching.
     */
    get: operations["geocode_api_geocode_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/property": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Property
     * @description Return property details for the given location.
     *
     *     Lookup strategy:
     *     1. Spatial search — closest property within ~100 m of (lat, lon).
     *     2. Street-name prefix match — first comma-delimited segment of address.
     *     3. Fall back to stub data.
     */
    get: operations["get_property_api_property_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/photos/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Photo
     * @description Stream a property photo from S3 storage.
     */
    get: operations["get_photo_api_photos__path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/comparables": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Comparables
     * @description Return comparable recently-sold properties near a given location.
     *
     *     Filters by radius, bedroom count (+/- 1), and square footage (+/- 25%).
     *     Results are ranked by a composite similarity score combining distance,
     *     size difference, and recency.
     */
    get: operations["get_comparables_api_comparables_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crime": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Crime
     * @description Return crime data for the area around the given location.
     */
    get: operations["get_crime_api_crime_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pois": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pois
     * @description Return points of interest near the given location.
     */
    get: operations["get_pois_api_pois_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/greenspace": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Greenspace
     * @description Return greenspace features and metrics near the given location.
     */
    get: operations["get_greenspace_api_greenspace_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/utilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Utilities
     * @description Return utility infrastructure features near the given location.
     */
    get: operations["get_utilities_api_utilities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/saved": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Saved
     * @description Return all saved properties for the authenticated user.
     */
    get: operations["list_saved_api_saved_get"];
    put?: never;
    /**
     * Save Property
     * @description Bookmark a property listing for the authenticated user.
     */
    post: operations["save_property_api_saved_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/saved/{saved_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update Saved
     * @description Update notes on a saved property. Must be the owner.
     */
    put: operations["update_saved_api_saved__saved_id__put"];
    post?: never;
    /**
     * Delete Saved
     * @description Remove a saved property. Must be the owner.
     */
    delete: operations["delete_saved_api_saved__saved_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/upload/redfin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload Redfin Html
     * @description Accept one or more Redfin HTML files and save to the configured directory.
     */
    post: operations["upload_redfin_html_api_upload_redfin_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cache/{prefix}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Cache
     * @description Invalidate all cached keys with the given prefix.
     *
     *     Requires authentication.  Returns the number of keys deleted.
     */
    delete: operations["delete_cache_api_cache__prefix__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Metrics
     * @description Endpoint that serves Prometheus metrics.
     */
    get: operations["metrics_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_login_api_auth_login_post */
    Body_login_api_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** Body_upload_redfin_html_api_upload_redfin_post */
    Body_upload_redfin_html_api_upload_redfin_post: {
      /** Files */
      files: string[];
    };
    /**
     * ClimateRisk
     * @description Climate risk assessment.
     */
    ClimateRisk: {
      /** Flood Risk */
      flood_risk: string;
      /** Flood Score */
      flood_score: number;
      /** Fire Risk */
      fire_risk: string;
      /** Fire Score */
      fire_score: number;
    };
    /**
     * ComparableProperty
     * @description A comparable property for comparison.
     */
    ComparableProperty: {
      /** Id */
      id: number;
      /** Address */
      address: string;
      /** Sale Price */
      sale_price: number;
      /** Sold Date */
      sold_date: string;
      /** Beds */
      beds: number;
      /** Baths */
      baths: number;
      /** Sqft */
      sqft: number;
      /** Price Per Sqft */
      price_per_sqft: number;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
    };
    /**
     * CrimeHeatmapPoint
     * @description A single heatmap data point.
     */
    CrimeHeatmapPoint: {
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Intensity */
      intensity: number;
    };
    /**
     * CrimeIncident
     * @description A single crime incident record.
     */
    CrimeIncident: {
      /** Id */
      id: string;
      /** Incident Type */
      incident_type: string;
      /** Category */
      category: string;
      /** Date */
      date: string;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Description */
      description?: string | null;
    };
    /**
     * CrimeMetrics
     * @description Aggregate crime metrics for the area.
     */
    CrimeMetrics: {
      /** Total Incidents 1Mi */
      total_incidents_1mi: number;
      /** Incidents Per 1000 People */
      incidents_per_1000_people: number;
      /** Crime Z Score */
      crime_z_score: number;
      /** Trend */
      trend: string;
    };
    /**
     * CrimeResponse
     * @description Response body for crime data lookup.
     */
    CrimeResponse: {
      /** Heatmap */
      heatmap: components["schemas"]["CrimeHeatmapPoint"][];
      /** Incidents */
      incidents: components["schemas"]["CrimeIncident"][];
      metrics: components["schemas"]["CrimeMetrics"];
    };
    /**
     * ExteriorFeatures
     * @description Exterior feature details.
     */
    ExteriorFeatures: {
      /** Roof */
      roof: string;
      /** Siding */
      siding: string;
      /** Foundation */
      foundation: string;
      /** Parking */
      parking: string;
      /** Pool */
      pool: boolean;
      /** Fence */
      fence: string;
    };
    /**
     * FeatureAttribution
     * @description A single feature's contribution to the predicted value.
     */
    FeatureAttribution: {
      /** Feature */
      feature: string;
      /** Display Name */
      display_name: string;
      /** Impact Dollars */
      impact_dollars: number;
    };
    /**
     * FinancialDetails
     * @description Financial information about the property.
     */
    FinancialDetails: {
      /** Hoa Monthly */
      hoa_monthly?: number | null;
      /** Tax Annual */
      tax_annual: number;
      /** Tax Year */
      tax_year: number;
      /** Assessed Value */
      assessed_value: number;
    };
    /**
     * ForecastRequest
     * @description Request body for a home value forecast.
     */
    ForecastRequest: {
      /** Address */
      address: string;
      /** City */
      city?: string | null;
      /** State */
      state?: string | null;
      /** Zip Code */
      zip_code?: string | null;
    };
    /**
     * ForecastResponse
     * @description Response body with predicted home value and confidence interval.
     */
    ForecastResponse: {
      /** Address */
      address: string;
      /** Predicted Value */
      predicted_value: number;
      /** Confidence Interval Low */
      confidence_interval_low: number;
      /** Confidence Interval High */
      confidence_interval_high: number;
      /** Model Version */
      model_version: string;
    };
    /**
     * GeocodeResponse
     * @description Response body for geocode lookups.
     */
    GeocodeResponse: {
      /** Results */
      results: components["schemas"]["GeocodeResult"][];
      /** Cached */
      cached: boolean;
    };
    /**
     * GeocodeResult
     * @description A single geocoding result.
     */
    GeocodeResult: {
      /** Display Name */
      display_name: string;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Place Id */
      place_id: number;
      /** Osm Type */
      osm_type: string;
      /** Osm Id */
      osm_id: number;
      /** Boundingbox */
      boundingbox: number[];
    };
    /**
     * GreenspaceFeature
     * @description A single greenspace feature.
     */
    GreenspaceFeature: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Feature Type */
      feature_type: string;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Distance Miles */
      distance_miles: number;
      /** Acreage */
      acreage?: number | null;
    };
    /**
     * GreenspaceMetrics
     * @description Aggregate greenspace metrics for the area.
     */
    GreenspaceMetrics: {
      /** Parks Within 1Mi */
      parks_within_1mi: number;
      /** Nearest Park Miles */
      nearest_park_miles: number;
      /**
       * Nearest Greenway Miles
       * @default 0
       */
      nearest_greenway_miles: number;
      /** Total Green Acres 1Mi */
      total_green_acres_1mi: number;
      /** Greenspace Z Score */
      greenspace_z_score: number;
    };
    /**
     * GreenspaceResponse
     * @description Response body for greenspace data lookup.
     */
    GreenspaceResponse: {
      /** Features */
      features: components["schemas"]["GreenspaceFeature"][];
      metrics: components["schemas"]["GreenspaceMetrics"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * InteriorFeatures
     * @description Interior feature details.
     */
    InteriorFeatures: {
      /** Flooring */
      flooring: string[];
      /** Appliances */
      appliances: string[];
      /** Heating */
      heating: string;
      /** Cooling */
      cooling: string;
      /** Fireplace */
      fireplace: boolean;
      /** Basement */
      basement?: string | null;
    };
    /**
     * PointOfInterest
     * @description A single point of interest.
     */
    PointOfInterest: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Category */
      category: string;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Distance Miles */
      distance_miles: number;
      /** Drive Minutes */
      drive_minutes: number;
    };
    /**
     * PoisMetrics
     * @description Aggregate metrics for POI results.
     */
    PoisMetrics: {
      /** Total Count */
      total_count: number;
      /** Categories Represented */
      categories_represented: number;
      /** Nearest Distance Miles */
      nearest_distance_miles: number | null;
    };
    /**
     * PoisResponse
     * @description Response body for points of interest lookup.
     */
    PoisResponse: {
      /** Pois */
      pois: components["schemas"]["PointOfInterest"][];
      metrics?: components["schemas"]["PoisMetrics"] | null;
    };
    /**
     * PropertyDetails
     * @description Core property details.
     */
    PropertyDetails: {
      /** Address */
      address: string;
      /** City */
      city: string;
      /** State */
      state: string;
      /** Zip Code */
      zip_code: string;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Bedrooms */
      bedrooms: number;
      /** Bathrooms */
      bathrooms: number;
      /** Sqft */
      sqft: number;
      /** Lot Size Sqft */
      lot_size_sqft: number;
      /** Year Built */
      year_built: number;
      /** Property Type */
      property_type: string;
      /** Stories */
      stories: number;
      /** Garage Spaces */
      garage_spaces: number;
      /** Description */
      description: string;
      /** Highlights */
      highlights: string[];
      /** Images */
      images: components["schemas"]["PropertyImage"][];
      /** Listing Status */
      listing_status?: string | null;
    };
    /**
     * PropertyImage
     * @description A single property image.
     */
    PropertyImage: {
      /** Url */
      url: string;
      /** Alt */
      alt: string;
      /**
       * Is Primary
       * @default false
       */
      is_primary: boolean;
    };
    /**
     * PropertyResponse
     * @description Response body for property lookup.
     */
    PropertyResponse: {
      property: components["schemas"]["PropertyDetails"];
      valuation: components["schemas"]["ValuationData"];
      interior: components["schemas"]["InteriorFeatures"];
      exterior: components["schemas"]["ExteriorFeatures"];
      financial: components["schemas"]["FinancialDetails"];
      /** Schools */
      schools: components["schemas"]["SchoolNearby"][];
      /** Sale History */
      sale_history: components["schemas"]["SaleHistoryEntry"][];
      /** Tax History */
      tax_history: components["schemas"]["TaxHistoryEntry"][];
      climate_risk: components["schemas"]["ClimateRisk"];
    };
    /**
     * SaleHistoryEntry
     * @description A single sale history event.
     */
    SaleHistoryEntry: {
      /** Date */
      date: string;
      /** Price */
      price: number;
      /** Event Type */
      event_type: string;
    };
    /**
     * SavedPropertyCreate
     * @description Request body to save/bookmark a property.
     */
    SavedPropertyCreate: {
      /** Listing Id */
      listing_id: number;
      /** Notes */
      notes?: string | null;
    };
    /**
     * SavedPropertyResponse
     * @description Single saved-property record returned to the client.
     */
    SavedPropertyResponse: {
      /** Id */
      id: number;
      /** Listing Id */
      listing_id: number;
      /** Notes */
      notes?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Listing Address */
      listing_address?: string | null;
    };
    /**
     * SavedPropertyUpdate
     * @description Request body to update notes on a saved property.
     */
    SavedPropertyUpdate: {
      /** Notes */
      notes?: string | null;
    };
    /**
     * SchoolNearby
     * @description A nearby school.
     */
    SchoolNearby: {
      /** Name */
      name: string;
      /** Address */
      address?: string | null;
      /** School Type */
      school_type: string;
      /** Rating */
      rating: number;
      /** Distance Miles */
      distance_miles: number;
      /** Drive Minutes */
      drive_minutes: number;
      /** Walk Minutes */
      walk_minutes?: number | null;
    };
    /**
     * TaxHistoryEntry
     * @description A single tax history record.
     */
    TaxHistoryEntry: {
      /** Year */
      year: number;
      /** Assessed Value */
      assessed_value: number;
      /** Tax Amount */
      tax_amount: number;
    };
    /**
     * TokenResponse
     * @description JWT token response from login.
     */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /**
     * UserCreate
     * @description Request body for user registration.
     */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Display Name */
      display_name?: string | null;
    };
    /**
     * UserResponse
     * @description Public user profile returned by API.
     */
    UserResponse: {
      /** Id */
      id: number;
      /** Email */
      email: string;
      /** Display Name */
      display_name?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Created At */
      created_at?: string | null;
    };
    /**
     * UserUpdate
     * @description Request body for updating user profile.
     */
    UserUpdate: {
      /** Display Name */
      display_name?: string | null;
    };
    /**
     * UtilitiesMetrics
     * @description Aggregate utilities metrics for the area.
     */
    UtilitiesMetrics: {
      /** Nearest Highway Miles */
      nearest_highway_miles: number;
      /** Nearest Railroad Miles */
      nearest_railroad_miles: number;
      /** Nearest Powerline Miles */
      nearest_powerline_miles: number;
      /** Nuisance Score */
      nuisance_score: number;
    };
    /**
     * UtilitiesResponse
     * @description Response body for utilities data lookup.
     */
    UtilitiesResponse: {
      /** Features */
      features: components["schemas"]["UtilityFeature"][];
      metrics: components["schemas"]["UtilitiesMetrics"];
    };
    /**
     * UtilityFeature
     * @description A single utility infrastructure feature.
     */
    UtilityFeature: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Feature Type */
      feature_type: string;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Distance Miles */
      distance_miles: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * ValuationData
     * @description Property valuation and prediction data.
     */
    ValuationData: {
      /** Listed Price */
      listed_price?: number | null;
      /** Last Sold Price */
      last_sold_price?: number | null;
      /** Last Sold Date */
      last_sold_date?: string | null;
      /** Redfin Estimate */
      redfin_estimate?: number | null;
      /** Predicted Value */
      predicted_value?: number | null;
      /** Confidence Interval Low */
      confidence_interval_low?: number | null;
      /** Confidence Interval High */
      confidence_interval_high?: number | null;
      /** Model Version */
      model_version?: string | null;
      /** Prediction Date */
      prediction_date?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  register_api_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  update_me_api_auth_me_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  google_login_api_auth_google_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  google_callback_api_auth_google_callback_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
    };
  };
  forecast_api_forecast_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForecastRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForecastResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  feature_importance_api_forecast_importance__property_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        property_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureAttribution"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  geocode_api_geocode_get: {
    parameters: {
      query: {
        q: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GeocodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_property_api_property_get: {
    parameters: {
      query: {
        lat: number;
        lon: number;
        address: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PropertyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_photo_api_photos__path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_comparables_api_comparables_get: {
    parameters: {
      query: {
        lat: number;
        lon: number;
        beds: number;
        sqft: number;
        radius_miles?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComparableProperty"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_crime_api_crime_get: {
    parameters: {
      query: {
        lat: number;
        lon: number;
        radius_miles?: number;
        days_back?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CrimeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_pois_api_pois_get: {
    parameters: {
      query: {
        lat: number;
        lon: number;
        radius_miles?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PoisResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_greenspace_api_greenspace_get: {
    parameters: {
      query: {
        lat: number;
        lon: number;
        radius_miles?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GreenspaceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_utilities_api_utilities_get: {
    parameters: {
      query: {
        lat: number;
        lon: number;
        radius_miles?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UtilitiesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_saved_api_saved_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedPropertyResponse"][];
        };
      };
    };
  };
  save_property_api_saved_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedPropertyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedPropertyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_saved_api_saved__saved_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        saved_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedPropertyUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedPropertyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_saved_api_saved__saved_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        saved_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_redfin_html_api_upload_redfin_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_redfin_html_api_upload_redfin_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_cache_api_cache__prefix__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        prefix: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  metrics_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
